server:
  port: 7001

spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy/MM/dd HH:mm:ss
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: org.postgresql.Driver
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    username: root
    #url: jdbc:postgresql://192.168.189.131:5432/postgres?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    url: jdbc:mysql://192.168.189.131:3306/seata?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
    lazy-loading-enabled: false
    aggressive-lazy-loading: true
    multiple-result-sets-enabled: true
    use-generated-key: true
    auto-mapping-behavior: PARTIAL
    default-executor-type: SIMPLE
    map-underscore-to-camel-case: true
    loca-cache-scope: SESSION
    jdbc-type-for-null: NULL
    log-prefix: mybatis_sql.


ribbon:
  okhttp:
    enabled: true
feign:
  httpclient:
    connection-timeout: 100


