spring:
  profiles:
    active: dev
  application:
    name: nacos-consumer-feign
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  sentinel:
    enabled: true

logging:
  level:
    root: info
    java.sql: debug
    org.springframework.web: trace
    org.mybatis: debug
